# Generated by Django 6.0.5 on 2026-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attendance_time_out_attendance_work_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='17:00')),
                ('grace_period', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'إعدادات الدوام',
            },
        ),
    ]
